<h1><?= $this->title ?></h1>
<a href="/news/add">Create news</a>
<?php
if (!is_null($this->news)) { ?>
    <table>
        <tr>
            <th>Title</th>
            <th></th>
        </tr>
        <?php
        foreach ($this->news as $news) { ?>
            <tr>
                <td><?= $news->title ?></td>
                <td>
                    <form action="" method="delete">
                        <button type="submit">Delete</button>
                    </form>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php
} ?>